import type { Metadata } from 'next';
import 'bootstrap/dist/css/bootstrap.css';
import 'swiper/css';
import 'swiper/css/navigation';
import 'bootstrap-icons/font/bootstrap-icons.css';
import '@/styles/global.min.css';
import '@/styles/theme.scss';
import './global.css';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
// import localFont from 'next/font/local';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
// });

export const metadata: Metadata = {
  title: 'Hkound',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
